### ISSUE TITLE
Error when evaluating on PCD

### ISSUE THREAD

**Issue by mikel-brostrom** [Herrccc/DR-TANet#5]
I started a training with:

`python3 train.py --dataset pcd --datadir ../path/to/TSUNAMI --checkpointdir ./ckpt --max-epochs 100 --batch-size 16 --encoder-arch resnet18 --local-kernel-size 1`

I then triggered the evaluation by:

`python3 eval.py --dataset pcd --datadir ./path/to/TSUNAMI --checkpointdir ./ckpt --result ./result --encoder-arch resnet18 --drtam --refinement --store-imgs`

But I get the following error:

```
Dynamic Receptive Temporal Attention Network (DR-TANet)
Encoder:resnet18
Adding refinement...
Reading model ... /xxx/DR-TANet/ckpt/TANet_k=1_resnet18/pcd/set0/checkpointdir/00000140.pth
Attention Layer-kernel size:7,stride:1,padding:3,groups:4...
Attention with refinement...
Attention Layer-kernel size:5,stride:1,padding:2,groups:4...
Attention with refinement...
Attention Layer-kernel size:3,stride:1,padding:1,groups:4...
Attention with refinement...
Attention Layer-kernel size:1,stride:1,padding:0,groups:4...
Attention with refinement...
Upsample layer: in = 1024, skip = 512, out = 512
Upsample layer: in = 512, skip = 256, out = 256
Upsample layer: in = 256, skip = 128, out = 128
Upsample layer: in = 128, skip = 64, out = 64
Traceback (most recent call last):
  File "eval.py", line 248, in <module>
    eval.run(set)
  File "eval.py", line 152, in run
    super(evaluate_pcd,self).run()
  File "eval.py", line 135, in run
    self.model.load_state_dict(torch.load(self.fn_model))
  File "/xxx/venvs/scd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1406, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for TANet:
        size mismatch for attention_module.attention_layer1.rel_h: copying a param with shape torch.Size([32, 1, 1, 1, 1]) from checkpoint, the shape in current model is torch.Size([32, 1, 1, 7, 1]).
        size mismatch for attention_module.attention_layer1.rel_w: copying a param with shape torch.Size([32, 1, 1, 1, 1]) from checkpoint, the shape in current model is torch.Size([32, 1, 1, 1, 7]).
        size mismatch for attention_module.attention_layer2.rel_h: copying a param with shape torch.Size([64, 1, 1, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 1, 1, 5, 1]).
        size mismatch for attention_module.attention_layer2.rel_w: copying a param with shape torch.Size([64, 1, 1, 1, 1]) from checkpoint, the shape in current model is torch.Size([64, 1, 1, 1, 5]).
        size mismatch for attention_module.attention_layer3.rel_h: copying a param with shape torch.Size([128, 1, 1, 1, 1]) from checkpoint, the shape in current model is torch.Size([128, 1, 1, 3, 1]).
        size mismatch for attention_module.attention_layer3.rel_w: copying a param with shape torch.Size([128, 1, 1, 1, 1]) from checkpoint, the shape in current model is torch.Size([128, 1, 1, 1, 3]).
```

**Comment by mikel-brostrom** [comment]
So, when running:

`python3 train.py --dataset pcd --datadir ../path/to/TSUNAMI --checkpointdir ./ckpt --max-epochs 100 --batch-size 16 --encoder-arch resnet18 --local-kernel-size 1`

(note there is no `--drtam` flag) which mean that **you train a TANet model**, not DRTANet.

Then this:

`python3 eval.py --dataset pcd --datadir ./path/to/TSUNAMI --checkpointdir ./ckpt --result ./result --encoder-arch resnet18 --drtam --refinement --store-imgs`

**tries to load TANet weights into a DR-TANet architectrue which results in the error.** That is why the original commands under the REAMDME file do not work. I suggest you to update the commands to that they do not trigger the error by default
